Add output of stdout/err

diff --git a/atlas-lsf b/atlas-lsf
--- a/atlas-lsf
+++ b/atlas-lsf
@@ -12,6 +12,7 @@ usageOpts="[ -c <command string> ] \
            [ -g <job group name, defaults to cluster default ] \
            [ -l <log prefix, no logs written by default ] \
            [ -m <monitor submitted job? Defaults to yes> ] \
+           [ -s <monitor style: 'status' for job status updates on polling, 'std_out_err' to report ongoing content of logs (where used). Defaults to std_out_err> ] \
            [ -f <poll frequency in seconds if job is monitored. Defaults to 10.> ] \
            [ -q <lsf queue, defaults to cluster default ]"
 
@@ -30,8 +31,9 @@ jobGroupName=
 logPrefix=
 monitorJob=yes
 pollFreqSecs=10
+monitorStyle=std_out_err
 
-while getopts ":c:w:m:p:j:g:l:n:f:q:" o; do
+while getopts ":c:w:m:p:j:g:l:n:f:q:s:" o; do
     case "${o}" in
         c)
             commandString=${OPTARG}
@@ -63,6 +65,9 @@ while getopts ":c:w:m:p:j:g:l:n:f:q:" o; do
         f)
             pollFreqSecs=${OPTARG}
             ;;
+        s)
+            monitorStyle=${OPTARG}
+            ;;
         *)
             usage
             exit 0
@@ -86,9 +91,9 @@ else
             logFile=${logPrefix}.out
         fi 
 
-        finalStatus=$(lsf_monitor_job "$lsfJobId" "$pollFreqSecs" "$logFile")
-        if [ "$finalStatus" != 'DONE' ]; then
-            die "Command \"$commandString\" failed, status $finalStatus"
+        lsf_monitor_job "$lsfJobId" "$pollFreqSecs" "$logFile" "$monitorStyle"
+        if [ $? -ne 0 ]; then
+            die "Command \"$commandString\" failed"
         fi
     fi
 fi
