Update atlas-slurm
Co-authored-by: Pedro Madrigal <8195212+pmb59@users.noreply.github.com>

diff --git a/atlas-slurm b/atlas-slurm
--- a/atlas-slurm
+++ b/atlas-slurm
@@ -105,7 +105,7 @@ elif [ -z "$workingDir" ]; then
 fi
 
 if [[ ! -d "${workingDir}" ]]; then
-    mkdir -p $workingDir
+    mkdir -p "$workingDir" || die "Failed to create directory: $workingDir"
 fi
 
 # Submit the jobs
