Pass exit codes better, return STDOUT, add quiet

diff --git a/atlas-lsf b/atlas-lsf
--- a/atlas-lsf
+++ b/atlas-lsf
@@ -13,9 +13,11 @@ usageOpts="[ -c <command string> ] \
            [ -l <log prefix, no logs written by default> ] \
            [ -e <clean up log files after monitored run? Defaults to no> ] \
            [ -n <monitor submitted job? Defaults to yes> ] \
+           [ -o <with -l, print standard output content? Defaults to no> ] \
            [ -s <monitor style: 'status' for job status updates on polling, 'std_out_err' to report ongoing content of logs (where used). Defaults to std_out_err> ] \
            [ -f <poll frequency in seconds if job is monitored. Defaults to 10.> ] \
            [ -q <lsf queue, defaults to cluster default> ] \
+           [ -u <suppress logging output? Default: no> ] \
            [ -v <name of the conda environment in which to run the job> ]"
 
 usageOpts=$(echo -e "$usageOpts" | tr -s " ")
@@ -31,13 +33,15 @@ jobName=
 queue=
 jobGroupName=
 logPrefix=
+returnStdout=no
 logCleanup=no
 monitorJob=yes
 pollFreqSecs=10
 monitorStyle=std_out_err
 prioritise=no
+quiet=no
 
-while getopts ":c:w:m:p:j:g:l:e:n:f:q:s:r:v:" o; do
+while getopts ":c:w:m:p:j:g:l:o:e:n:f:q:s:r:v:u:" o; do
     case "${o}" in
         c)
             commandString=${OPTARG}
@@ -78,8 +82,14 @@ while getopts ":c:w:m:p:j:g:l:e:n:f:q:s:r:v:" o; do
         r)
             prioritise=${OPTARG}
             ;;
+        o)
+            returnStdout=${OPTARG}
+            ;;
         v)
             condaEnv=${OPTARG}
+            ;;
+        u)
+            quiet=${OPTARG}
             ;;
         *)
             usage
@@ -96,7 +106,7 @@ submitStatus=$?
 if [ "$submitStatus" -ne "0" ] && [ -n "$lsfJobId" ]; then
     die "Job submission failed, status is $submitStatus"
 else
-    echo "Job submission succeeded, received job ID $lsfJobId"
+    warn "Job submission succeeded, received job ID $lsfJobId" "$quiet"
     
     if [ "$monitorJob" = 'yes' ]; then
         logFile=
@@ -104,10 +114,11 @@ else
             logFile=${logPrefix}.out
         fi 
 
-        lsf_monitor_job "$lsfJobId" "$pollFreqSecs" "$logFile" "$monitorStyle" "$logCleanup"
+        lsf_monitor_job "$lsfJobId" "$pollFreqSecs" "$logFile" "$monitorStyle" "$logCleanup" "$returnStdout" "$quiet"
+        lsfExitCode=$?
 
-        if [ $? -ne 0 ]; then
-            die "Command \"$commandString\" failed"
+        if [ $lsfExitCode -ne 0 ]; then
+            die "Command \"$commandString\" failed" "$lsfExitCode" "$quiet"
         fi
     fi
 fi
